version: '3.7'

services:

  x-redis:
    image: redislabs/redisgraph
    ports:
      - 6379:6379

  x-adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
      
  x-redis-bloom:
    image: redislabs/rebloom
    ports:
      - 6380:6379

  x-redis-ai:
    image: redisai/redisai
    ports:
      - 6381:6379

  x-redis-timeseries:
    image: redislabs/redistimeseries
    ports:
      - 6382:6379
  
  x-keycloak:
    image: jboss/keycloak
    command: ["-Dkeycloak.migration.action=import",
     "-Dkeycloak.migration.provider=dir",
      "-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config",
       "-Dkeycloak.migration.strategy=IGNORE_EXISTING"]
    volumes:
      - ./realm-config:/opt/jboss/keycloak/realm-config
      - ./keycloak-db:/opt/jboss/keycloak/standalone/data
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8880:8080

volumes:
  ivy2:
    driver_opts:
      o: bind
      type: none
      device: $HOME/.ivy2
  sbt:
    driver_opts:
      o: bind
      type: none
      device: $HOME/.sbt
      